# Generated by Django 3.0.5 on 2020-04-10 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('aadhar', models.BigIntegerField()),
                ('mobile', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('come_by', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='')),
                ('sample', models.IntegerField()),
                ('positive', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('pending', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('discharged', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosApp.Hospital')),
            ],
        ),
    ]
