# Generated by Django 3.0.5 on 2020-04-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosApp', '0002_auto_20200410_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(default='ss', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='admit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
