# Generated by Django 3.0.5 on 2020-04-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosApp', '0003_auto_20200411_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
