# Generated by Django 3.0.5 on 2020-04-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosApp', '0004_auto_20200411_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('pin', models.IntegerField()),
                ('ifsc', models.CharField(max_length=20)),
                ('allowed', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=20)),
                ('time', models.IntegerField()),
            ],
        ),
    ]
